apiVersion: k8spin.cloud/v1
kind: Organization
metadata:
  name: aabbccdd
spec:
  resources:
    cpu: "10"
    memory: "10G"
  # By default the organization name could be used to access the organization if the certificate include the name in the certificate filed O=
  roles:
    - name: organization-admin # Cluster Role
      groups: ["K8Spin.cloud"] # User Certificate O=
    - name: organization-admin # Cluster Role
      users: ["Hadiwinata", "Yusuf"] # User Certificate CN=
[root@helper examples]# cat tenant-1-aabbccdd.yaml 
apiVersion: k8spin.cloud/v1
kind: Tenant
metadata:
  namespace: org-aabbccdd
  name: app1
spec:
  resources:
    cpu: "3"
    memory: "3G"
  roles:
    - name: tenant-admin # Cluster Role
      groups: ["K8Spin.cloud"] # User Certificate O=
    - name: tenant-viewer # Cluster Role
      users: ["Angel", "Pau"] # User Certificate CN=
